api_id: ENC[AES256_GCM,data:zkEVHSH7xtc=,iv:BvNUeizQsTJZ6VVH5c81xq2voK/HJP2poHaDTGwTexs=,tag:/Yh9WVHZLkQcrIngV4+Haw==,type:int]
api_hash: ENC[AES256_GCM,data:LZdqvmvJ9TxT0CSkit6At53pJmdcOpb3EYL7v+G83Jg=,iv:MXfijuUm13UbYfcqJvh4fF8GBUfQxe9RJzzkxXn9OdE=,tag:htdsI1VWzlSkE+dwygYo+Q==,type:str]
aws_access_key_id: ENC[AES256_GCM,data:EHAq4DwsYnoErNCj1nsgK8jFdYKBOVI0YA==,iv:I1Hk+WcsC/zZOkjlPQLc7cxaEKzQAOgmn4xHW/bjpAc=,tag:7tNWkkOM/10DDRKDiM6v0w==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:ZwzfKTYlak4eow5yhuFoQmCJZ2gBcJ6xXseh4f3ddyN5HjjTlEnrGg==,iv:TuQukxPx727masRT6/B8mp5SkvSinmAnKrH5p/QCLXQ=,tag:IvbGrYsnXdrWmazC0l5RGQ==,type:str]
s3_endpoint_url: ENC[AES256_GCM,data:7cXzpUcZ39o9l3q0COW48tu2Wb7JhgMNrb4hCA8F8g==,iv:OR/PJ5YBaTixoclNYHEw4i4ZDDtUAsyYzz2UUNODfao=,tag:86VvvEdeYduG+jFNfKEIZw==,type:str]
bucket_name: ENC[AES256_GCM,data:n81vg9tfmhCc,iv:j8QM2x0xgxgDt5dZbG0dhUTipkkhlx+8Nsc6zxSi5xI=,tag:DajNxw45A3C2hgxZSdk9EQ==,type:str]
region_name: ENC[AES256_GCM,data:KUc9cs8IOrezMjA=,iv:kTHZOc4G2Jxf2QczC1fXnLOV3ygXKl7Vs5/D6YFnSCA=,tag:xcc7yiETyT/5gMYT+nFz3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-01T09:20:39Z"
    mac: ENC[AES256_GCM,data:zEGw4eM9o0TWxTyRGPuXs5f6vxyepSIYZ/ABgH8lgbLW/SIap8ZMi9SfV31Jk9rC/PkihW8JRXIk+D7UOskJu+NWaqEc2TA8OwjTiLVXS1vwSv/9x2OnvW/lxS8c1Jnv4QBvkvIE5fNRtnelbB5DoO+F0nBS3jYMBHx0A3GV8yw=,iv:Rc1AIDDBOXeaTPUyPMW7aPv5fQ96y3+DR3LmGi+yQfQ=,tag:gER7D2h6Axjxe2TKJoBT1w==,type:str]
    pgp:
        - created_at: "2024-11-01T08:28:11Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzjAwDQER4/9AQwAw7NDKCtXNUqouOMDOHdz5uum0iYBDvPaQHLcca9nSEYM
            Avy2FXFy8gvaL8YmApyzigrsgthnSGr4tzdchW08nGtb4TbGHluUxuR/ocxBPHTr
            4SIRuu44atOSkQXCyIhptDgMZZxsFZukTOOOByznAtj/P5LUg+9vC7gZ/mXIDC4f
            w4Dmm52uz1dHrOOLET/wnhJy6RTYT1labJ1phYOD881WRn8fOq7AIlTVfgnl76RP
            OHtnm7lT0w6qPQaI2yZsVsJfCTEGXMo6xJCF0u620I3ugfEsAhEZTaD43281KxxG
            6bubmVARAqTU+10F5yt/sXR6E9dkgmdSeZ4XT16DZmDNb8GEh7FSAE5go/dQHHWE
            eAdonMd61F1UUh959mqWnKq6pw88z//nN9ylxmiUEmrcasdhK5j6oZwXWYsi058r
            1T2fkmko/hhtg5ZlZu6A+LEELuWE8gwWm1yXSiKBWQwsQbUyUeN5zCJREKjRE8Xq
            wMdQ+ujW8kaUs1kCT/Mn0l4BXuDA/2f7xXsgKr8dfloQ8KMahJ3yfYXMxiEcuyex
            N9giYl3dQ5Zr0JWNmi/eJt+ea0/JpT0JNaOkrmUk3nyuN4nCA+PjfIMBl7Y9+rXx
            AACRd0QbyiCeJAcSXg7s
            =x3Jn
            -----END PGP MESSAGE-----
          fp: 201BF3CD9CBD8E1E807F5F46F3B6389D4F0EE909
    unencrypted_suffix: _unencrypted
    version: 3.7.1
