api_id: ENC[AES256_GCM,data:zkEVHSH7xtc=,iv:BvNUeizQsTJZ6VVH5c81xq2voK/HJP2poHaDTGwTexs=,tag:/Yh9WVHZLkQcrIngV4+Haw==,type:int]
api_hash: ENC[AES256_GCM,data:LZdqvmvJ9TxT0CSkit6At53pJmdcOpb3EYL7v+G83Jg=,iv:MXfijuUm13UbYfcqJvh4fF8GBUfQxe9RJzzkxXn9OdE=,tag:htdsI1VWzlSkE+dwygYo+Q==,type:str]
aws_access_key_id: ENC[AES256_GCM,data:EHAq4DwsYnoErNCj1nsgK8jFdYKBOVI0YA==,iv:I1Hk+WcsC/zZOkjlPQLc7cxaEKzQAOgmn4xHW/bjpAc=,tag:7tNWkkOM/10DDRKDiM6v0w==,type:str]
aws_secret_access_key: ENC[AES256_GCM,data:ZwzfKTYlak4eow5yhuFoQmCJZ2gBcJ6xXseh4f3ddyN5HjjTlEnrGg==,iv:TuQukxPx727masRT6/B8mp5SkvSinmAnKrH5p/QCLXQ=,tag:IvbGrYsnXdrWmazC0l5RGQ==,type:str]
s3_endpoint_url: ENC[AES256_GCM,data:7cXzpUcZ39o9l3q0COW48tu2Wb7JhgMNrb4hCA8F8g==,iv:OR/PJ5YBaTixoclNYHEw4i4ZDDtUAsyYzz2UUNODfao=,tag:86VvvEdeYduG+jFNfKEIZw==,type:str]
bucket_name: ENC[AES256_GCM,data:n81vg9tfmhCc,iv:j8QM2x0xgxgDt5dZbG0dhUTipkkhlx+8Nsc6zxSi5xI=,tag:DajNxw45A3C2hgxZSdk9EQ==,type:str]
region_name: ENC[AES256_GCM,data:KUc9cs8IOrezMjA=,iv:kTHZOc4G2Jxf2QczC1fXnLOV3ygXKl7Vs5/D6YFnSCA=,tag:xcc7yiETyT/5gMYT+nFz3Q==,type:str]
site_base: ENC[AES256_GCM,data:Uz7TO9hsdb1+rXUHzb5iXxUamcd8nTk=,iv:Ql0fg+2LMBSaRQZSJHg8qiD/RWW3/JLgKZEYG6v6O/s=,tag:1JWe1iViTePjAieLeZXHng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-03T16:43:57Z"
    mac: ENC[AES256_GCM,data:pHessh4eYOySIBJv5J5K/SQoG7KFc7imlDc5XnV8h63ROH4s0akeMm/clXOyH13vl8h48Uj7aB2S2pdLTtkK3Wpt3gBfgftybNxjJ1HV7xMiRsPItcu+xIf3cTFDOneTQhdrxYHfzt+8shT3M2t8FUICdujhVKL7AbYQ5fXR+mw=,iv:t22U46haELtSWLtB2S5wbXiYLitFuMnYoCJ8pL2AoIs=,tag:85uYHwzWq6Hg2N8m3hFzPA==,type:str]
    pgp:
        - created_at: "2024-11-01T17:52:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMAzjAwDQER4/9AQv/V//+iuUHizJMW7qbtBxk+DoYqIr8Vx0edyMl818lJ96G
            ZigISZmEvE5XiuAtQ/22KmWVoeETDkhnICFqwRxhYf1AHRM/P7rRlX0pMuIN9Rj7
            ZdrwmSln+wksheKcRxt4aMY2V9vyyQlJvMKbuR7Q1BZibon2wTbQTdoOSwpATT7r
            cNND0CsBwSWQcbIY7zRgARMD2HeFFc+eGj2IyTmrlbWnYEfhCnoYzm302jdyLmWn
            pysSKPhOfJpEf3kLn0SDnNbi6T297jCtQYpgLhWp+D6EkqROWY4dDeEpVuBosuQ/
            OBm8WOt68Yy4lTggUuRpAzBegOLNumNhZgGc7d+7zNkDm3ahM0By09nTADA098U9
            /J0uiOCZXu1Nc9Ox7lQQioXCFdkHeXaGRw+3F/6zUgQ5TR3i1sEKJjMdo+DON7gi
            SSmvIfbsOlT2zHyAVgi5ZKHUW0qYym8hFodElJDm5GGqdqR/M2gdIyn1hw5OtvC4
            0uXV1Wi/5L4zeZcMElhC0l4BVQtoup2ob10AX49UbGiYrGUH3bTzptR3JzpE/Xuk
            91M0nAEbcaB+hTF1gMKx4kogXFyf7b9H4CAcZA1JRk09f1VY0UAGPBwEG62cxlRd
            Qw0oMBRhl6EirJmqjGIc
            =JQWi
            -----END PGP MESSAGE-----
          fp: 201BF3CD9CBD8E1E807F5F46F3B6389D4F0EE909
        - created_at: "2024-11-01T17:52:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0+Ks1ofuFinAQv9F4YQUDsarBath01AqAMCsW1fQKQF99SdZGXTM5X51fZm
            ObtNfVQzxQ1BxssUS65mT599j9P0jDg46paRSgok22P5+es9NOQD9F18F2ds0LJU
            QaNCgvwnjXuDPQLao8cIP+ecwE9IjMI5xdGhRu5g0VBgV5NssuINMyFV+K1drub5
            wB8TVN80b4hdLyFT92w7diZ/c/0Oq9Pz/p9DLHOaROAEVAewdnhdHs/WYwXRQHRs
            NSKfhUO93qj20oWLaP1pUn+APqrsqYgSxl8TMBL8RHIja1qkJP6uQRkx4rYk1mDh
            Aw8MYw8f3Sbb2N/nE/XnBqUNUSqBQyBCJ1A77YiEuW4ollrpR6/NC0+cYrvp9F+7
            FHkNN+v0tSDt7y9Bu8vsfNCdRKtwBGgGvBMKdRcgzpLX/dXENVPe4p3sx5sYO0vM
            8sMWHtDlP/Fnty4x/9IsuyfgkIAR3k4uJQ+8HphNX7IxVOvWJHxhH1sQM30ZU4Yi
            MuxMPMK627tSsffyEQer0l4Bk1cvhGNm83bhckQHlsr/aL4PmZOeOBOwJFAKbP2L
            nRYDjtqJqQZFsKrTyzWiaMNIBoe87EYCMr7OL64yrMcSo5QGk2WdB2bxosSRZ2XU
            pC4o43tmYZKDlx78GjqF
            =MGIi
            -----END PGP MESSAGE-----
          fp: D54B4214225EBCDCA4C21468E931814179B11527
    unencrypted_suffix: _unencrypted
    version: 3.7.1
